# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20180111_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_position',
            field=models.IntegerField(null=True, verbose_name='banner position'),
        ),
    ]
