# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_auto_20180120_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner_position',
            field=models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th')], null=True, verbose_name='banner position'),
        ),
    ]
