# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_auto_20180120_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_offer',
            field=models.BooleanField(default=False, verbose_name='package offer'),
        ),
    ]
