# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_product_package_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='product.Product', verbose_name='battery for package offer')),
                ('coil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coil', to='product.Product', verbose_name='coil for package offer')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='product.Product', verbose_name='device for package offer')),
                ('eliquids', models.ManyToManyField(related_name='eliquids', to='product.Product', verbose_name='eliquids for package offer')),
            ],
        ),
    ]
