# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_packageoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageoffer',
            name='battery',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='product.Product', verbose_name='battery for package offer'),
        ),
        migrations.AlterField(
            model_name='packageoffer',
            name='coil',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='coil', to='product.Product', verbose_name='coil for package offer'),
        ),
    ]
