# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 11:11
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_auto_20180328_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageoffer',
            name='price',
            field=django_prices.models.PriceField(currency='AED', decimal_places=2, default=100, max_digits=12, verbose_name='price'),
            preserve_default=False,
        ),
    ]
