# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_auto_20180328_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='products', verbose_name='image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='ppoi')),
                ('alt', models.CharField(blank=True, max_length=128, verbose_name='short description')),
                ('order', models.PositiveIntegerField(editable=False, verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.PackageOffer', verbose_name='product')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
