# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-18 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_packageofferimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_package', to='product.Product')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_package', to='product.ProductClass')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_package', to='product.ProductVariant')),
            ],
        ),
        migrations.AlterField(
            model_name='packageoffer',
            name='battery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='product.Product', verbose_name='battery for package ProductVariantoffer'),
        ),
    ]
