# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-24 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_auto_20181217_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_package_info', to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productpackage',
            name='product_package_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_package', to='product.ProductPackageInfo'),
            preserve_default=False,
        ),
    ]
