# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-24 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_auto_20181224_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackageinfo',
            name='product_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.ProductClass'),
            preserve_default=False,
        ),
    ]
