# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 13:00
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20171129_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=django_prices.models.PriceField(currency='AED', decimal_places=2, default=0, max_digits=12, verbose_name='total'),
        ),
    ]
