# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-16 07:07
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20180111_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='package_offer_data',
            field=jsonfield.fields.JSONField(blank=True, default={}, verbose_name='package_offer_data'),
        ),
    ]
