# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 13:00
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20171218_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=django_prices.models.PriceField(blank=True, currency='AED', decimal_places=2, max_digits=12, null=True, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=django_prices.models.PriceField(currency='AED', decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='shipping price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_net',
            field=django_prices.models.PriceField(blank=True, currency='AED', decimal_places=2, max_digits=12, null=True, verbose_name='total net'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=django_prices.models.PriceField(blank=True, currency='AED', decimal_places=2, max_digits=12, null=True, verbose_name='total tax'),
        ),
    ]
