# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-17 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20180111_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_package_offer',
            field=models.BooleanField(default=False),
        ),
    ]
