# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-01 08:00
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_order_has_package_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default={}, verbose_name='data'),
        ),
    ]
